import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")
plt.figure(figsize=(6, 4))
sns.countplot(x='placement', data=df, palette='Set2')
plt.title('Placement Distribution')
plt.xlabel('Placement Status')
plt.ylabel('Number of Students')
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 6))
df_melted = df.melt(value_vars=marks_columns, var_name='Subject', value_name='Marks')
sns.boxplot(x='Subject', y='Marks', data=df_melted, palette='Set3')
plt.title('Subject-wise Marks Distribution')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
plt.figure(figsize=(7, 5))
sns.histplot(df['average'], bins=10, kde=True, color='skyblue')
plt.title('Distribution of Average Marks')
plt.xlabel('Average Marks')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()
plt.figure(figsize=(8, 6))
corr = df[marks_columns + ['average']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Subject Correlation Matrix')
plt.tight_layout()
plt.show()
placement_counts = df['placement'].value_counts()
plt.figure(figsize=(6, 6))
plt.pie(placement_counts, labels=placement_counts.index, autopct='%1.1f%%', colors=['lightgreen', 'lightcoral'])
plt.title('Placement Status (Pie Chart)')
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 5))
company_list = df['company'].str.split(", ").explode()
sns.countplot(y=company_list, order=company_list.value_counts().index, palette='viridis')
plt.title('Company-wise Student Count')
plt.xlabel('Number of Students')
plt.ylabel('Company')
plt.tight_layout()
plt.show()
df['company_count'] = df['company'].apply(lambda x: 0 if x == "None" else len(x.split(", ")))
plt.figure(figsize=(8, 5))
sns.scatterplot(x='average', y='company_count', hue='placement', data=df, palette='Set1')
plt.title('Average Marks vs Number of Eligible Companies')
plt.xlabel('Average Marks')
plt.ylabel('Eligible Company Count')
plt.tight_layout()
plt.show()
